In [1]:
import pandas as pd
import numpy as np
import os 
import pickle
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
os.chdir('/Users/hemangeebhatupatil/Documents/acmgrade_machine learning')

In [3]:
df=pd.read_csv('parkinsons.data')
display (df)

,name,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
0,phon_R01_S01_1,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,...,0.06545,0.02211,21.033,1,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,phon_R01_S01_2,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,...,0.09403,0.01929,19.085,1,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,phon_R01_S01_3,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,...,0.08270,0.01309,20.651,1,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,phon_R01_S01_4,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,...,0.08771,0.01353,20.644,1,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,phon_R01_S01_5,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,...,0.10470,0.01767,19.649,1,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,phon_R01_S50_2,174.188,230.978,94.261,0.00459,0.00003,0.00263,0.00259,0.00790,0.04087,...,0.07008,0.02764,19.517,0,0.448439,0.657899,-6.538586,0.121952,2.657476,0.133050
191,phon_R01_S50_3,209.516,253.017,89.488,0.00564,0.00003,0.00331,0.00292,0.00994,0.02751,...,0.04812,0.01810,19.147,0,0.431674,0.683244,-6.195325,0.129303,2.784312,0.168895
192,phon_R01_S50_4,174.688,240.005,74.287,0.01360,0.00008,0.00624,0.00564,0.01873,0.02308,...,0.03804,0.10715,17.883,0,0.407567,0.655683,-6.787197,0.158453,2.679772,0.131728
193,phon_R01_S50_5,198.764,396.961,74.904,0.00740,0.00004,0.00370,0.00390,0.01109,0.02296,...,0.03794,0.07223,19.020,0,0.451221,0.643956,-6.744577,0.207454,2.138608,0.123306
194,phon_R01_S50_6,214.289,260.277,77.973,0.00567,0.00003,0.00295,0.00317,0.00885,0.01884,...,0.03078,0.04398,21.209,0,0.462803,0.664357,-5.724056,0.190667,2.555477,0.148569

In [4]:
X=df.drop(labels=['status','name'],axis=1)
display (X.head())

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
0,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,0.426,...,0.02971,0.06545,0.02211,21.033,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,0.626,...,0.04368,0.09403,0.01929,19.085,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,0.482,...,0.03590,0.08270,0.01309,20.651,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,0.517,...,0.03772,0.08771,0.01353,20.644,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,0.584,...,0.04465,0.10470,0.01767,19.649,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335

In [5]:
Y=df['status']
display (Y.head())

0    1
1    1
2    1
3    1
4    1
Name: status, dtype: int64

In [6]:
model=pickle.load(open('deploy_SVM.pkl','rb'))
# Prediction 
prediction = model.predict (X)
print ( 'Accuracy ',accuracy_score (Y, prediction))
print ()
print ( 'Classification Report')
print (classification_report  (Y,prediction,zero_division=0))
print ( 'Confusion Matrix')
print (confusion_matrix  (Y,prediction))

Accuracy  0.882051282051282

Classification Report
              precision    recall  f1-score   support

           0       0.90      0.58      0.71        48
           1       0.88      0.98      0.93       147

    accuracy                           0.88       195
   macro avg       0.89      0.78      0.82       195
weighted avg       0.88      0.88      0.87       195

Confusion Matrix
[[ 28  20]
 [  3 144]]

In [7]:
result = pd.concat ([df['status'],pd.DataFrame (prediction,columns = ['Prediction'])],axis =1)
display (result.head(50))

    status  Prediction
0        1           1
1        1           1
2        1           1
3        1           1
4        1           1
5        1           1
6        1           1
7        1           1
8        1           1
9        1           1
10       1           1
11       1           1
12       1           1
13       1           1
14       1           1
15       1           1
16       1           1
17       1           1
18       1           1
19       1           1
20       1           1
21       1           1
22       1           1
23       1           1
24       1           1
25       1           1
26       1           1
27       1           1
28       1           0
29       1           1
30       0           0
31       0           0
32       0           0
33       0           0
34       0           0
35       0           0
36       1           1
37       1           1
38       1           1
39       1           1
40       1           1
41       1           0
42       0           0
43       0           0
44       0           0
45       0           0
46       0           0
47       0           0
48       0           1
49       0           1